version: '3'

services:
  app:
    build:
      context: .
      target: deps
    volumes:
      - .:/myapp
      - node_modules:/myapp/node_modules/
      - app-data:/data
    ports:
      - 3003:8080
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/data/sqlite.db
    command: npm run dev

volumes:
  node_modules: